id: config-properties

info:
  name: config.properties Disclosure
  author: SirBugs
  severity: medium
  description: This Template checks disclosing secret information via /config.properties
  tags: config, secrets, leaks

requests:
  - method: GET
    path:
      - '{{BaseURL}}/config.properties'
      - '{{BaseURL}}/ui_config.properties'
      - '{{BaseURL}}/config-user.properties'
      - '{{BaseURL}}/microprofile-config.properties'
      - '{{BaseURL}}/config.properties.bak'
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '#/home'
          - 'ttfDir='
          - '.mysql.'
          - 'SELECT * FROM'
          - 'jdbc'
