id: web-config
info:
  name: Web Config file
  author: Yash Anand @yashanand155
  severity: info

requests:
  - method: GET
    path:
      - '{{BaseURL}}/web.config'
      - '{{BaseURL}}/config.web'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - <configuration>
          - <system.webServer>
        condition: and

      - type: status
        status:
          - 200